generatorName: python
inputSpec: kandji_openapi.yaml
outputDir: .
verbose: False
skipOverwrite: True
useTags: True
enablePostProcessFile: True
packageName: kandji_python_sdk
# apiNamePrefix: ''
# apiNameSuffix: Api
gitHost: github.com
gitRepoId: kandji-python-sdk
gitUserId: MScottBlake
