name: 1 Generate SDK

on:
  workflow_dispatch:
  repository_dispatch:
    types: [generate-sdk]

jobs:
  generate_sdk:
    runs-on: ubuntu-latest
    env:
      language: python
      openapi_file: kandji_openapi.yaml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.KANDJI_OPENAPI_TOKEN }}

      - name: Delete Generated Files
        run: |
          rm -rf .github/workflows/${{ env.language }}.yml \
            .gitlab-ci.yml \
            .openapi-generator-ignore \
            .travis.yml \
            git_push.sh \
            pyproject.toml \
            README.md \
            requirements.txt \
            setup.cfg \
            setup.py \
            test-requirements.txt \
            tox.ini \
            docs \
            kandji_${{ env.language }}_sdk \
            test \


      - name: Download Kandji OpenAPI file
        env:
          GH_TOKEN: ${{ secrets.KANDJI_OPENAPI_TOKEN }}
        run: |
          gh release download \
            --repo "MScottBlake/kandji-openapi-spec" \
            --pattern "kandji_openapi\.yaml" \
            --output "${{ env.openapi_file }}"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openapi_file
          path: ${{ env.openapi_file }}

      - name: Generate Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          config-file: kandji-generator-config.yaml
          generator: ${{ env.language }}
          generator-tag: latest-release
          openapi-file: ${{ env.openapi_file }}

      - name: Move the output client to repo root
        run: |
          mv ${{ env.language }}-client/{*,.*} ${{ env.language }}-client/../ 2>/dev/null
          rmdir ${{ env.language }}-client

      - name: Delete Kandji OpenAPI file
        run: |
          rm -rf "${{ env.openapi_file }}"

      - name: Check for Changes
        id: check_changes
        run: |
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes to commit."
            echo "continue=false" >> $GITHUB_ENV
          else
            echo "Changes detected."
            echo "continue=true" >> $GITHUB_ENV
          fi

      - name: Create Pull Request
        if: env.continue == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          sign-commits: true
          commit-message: "[auto] Updated Kandji SDK"
          branch: update-sdk
          base: main
          delete-branch: true
          title: "[auto] Updated Kandji SDK"
